In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset=pd.read_csv("ckd.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [3]:
#eliminate an unwanted columns
#dataset=dataset.drop("column name", axis=1) Default axis =0 (row) 1 (column)

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]
depen=dataset[['classification_yes']]

In [6]:
indep.shape

(399, 27)

In [7]:
dataset.dtypes

age                   float64
bp                    float64
al                    float64
su                    float64
bgr                   float64
bu                    float64
sc                    float64
sod                   float64
pot                   float64
hrmo                  float64
pcv                   float64
wc                    float64
rc                    float64
sg_b                    uint8
sg_c                    uint8
sg_d                    uint8
sg_e                    uint8
rbc_normal              uint8
pc_normal               uint8
pcc_present             uint8
ba_present              uint8
htn_yes                 uint8
dm_yes                  uint8
cad_yes                 uint8
appet_yes               uint8
pe_yes                  uint8
ane_yes                 uint8
classification_yes      uint8
dtype: object

In [8]:
depen.shape

(399, 1)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,depen,test_size=0.30,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid={'penalty':['l2'],'solver':['lbfgs', 'liblinear', 'newton-cg', 'saga']}
grid=GridSearchCV(LogisticRegression(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Users\Admin\anaconda3\envs\virenvo\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg', 'saga']},
             scoring='f1_weighted', verbose=3)

In [13]:
#print best parameter after tunning
print(grid.best_params_)

{'penalty': 'l2', 'solver': 'lbfgs'}

In [14]:
#print the result
re=grid.cv_results_
print(re)

{'mean_fit_time': array([0.53345227, 0.21839271, 0.16229239, 0.12682533]), 'std_fit_time': array([0.        , 0.13952316, 0.08383545, 0.02878396]), 'mean_score_time': array([0.        , 0.01923976, 0.00119896, 0.00717897]), 'std_score_time': array([0.        , 0.01470668, 0.00040021, 0.0082712 ]), 'param_penalty': masked_array(data=['l2', 'l2', 'l2', 'l2'],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'param_solver': masked_array(data=['lbfgs', 'liblinear', 'newton-cg', 'saga'],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'penalty': 'l2', 'solver': 'lbfgs'}, {'penalty': 'l2', 'solver': 'liblinear'}, {'penalty': 'l2', 'solver': 'newton-cg'}, {'penalty': 'l2', 'solver': 'saga'}], 'split0_test_score': array([0.9822211 , 0.96457219, 0.9822211 , 0.9822211 ]), 'split1_test_score': array([1.       , 0.9822211, 1.       , 0.9822211]), 'split2_test_score': array([0.9822211 , 0.96457219, 0.9822211 , 0.96457219]), 'split3_test_score': array([1.        , 0.96457219, 1.        , 0.9822211 ]), 'split4_test_score': array([1.        , 0.98189391, 1.        , 0.98189391]), 'mean_test_score': array([0.99288844, 0.97156632, 0.99288844, 0.97862588]), 'std_test_score': array([0.00870985, 0.00856664, 0.00870985, 0.00702799]), 'rank_test_score': array([1, 4, 1, 3])}

In [15]:
grid_predictions=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [16]:
print("The Confusion Matrix:\n", cm)

The Confusion Matrix:
 [[45  0]
 [ 1 74]]

In [17]:
print("The report:\n", clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, grid.predict_proba(x_test)[:,1])

1.0

In [19]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.533452,0.000000,0.000000,0.000000,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
1,0.218393,0.139523,0.019240,0.014707,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",0.964572,0.982221,0.964572,0.964572,0.981894,0.971566,0.008567,4
2,0.162292,0.083835,0.001199,0.000400,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
3,0.126825,0.028784,0.007179,0.008271,l2,saga,"{'penalty': 'l2', 'solver': 'saga'}",0.982221,0.982221,0.964572,0.982221,0.981894,0.978626,0.007028,3

In [20]:
age=int(input("Age:"))
bp=int(input("bp:"))
al=int(input("al:"))
su=int(input("su:"))
bgr=int(input("bgr:"))
bu=float(input("bu:"))
sc=float(input("sc:"))
sod=int(input("sod:"))
pot=float(input("pot:"))
hrmo=int(input("hrmo:"))
pcv=int(input("pcv:"))
wc=int(input("wc:"))
rc=int(input("rc:"))
sg_b=int(input("sg_b:"))
sg_c=int(input("sg_c:"))
sg_d=int(input("sg_d:"))
sg_e=int(input("sg_d:"))
rbc_normal=int(input("rbc_normal:"))
pc_normal=int(input("pc_normal:"))
pcc_present=int(input("pcc_present:"))
ba_present=int(input("ba_present:"))
htn_yes=int(input("htn_yes:"))
dm_yes=int(input("dm_yes:"))
cad_yes=int(input("cad_yes:"))
appet_yes=int(input("appet_yes:"))
pe_yes=int(input("pe_yes:"))
ane_yes=int(input("ane_yes:"))

Age: 39
bp: 87
al: 0
su: 0
bgr: 143
bu: 3.2
sc: 0.2
sod: 32
pot: 3.4
hrmo: 12
pcv: 34
wc: 142
rc: 12
sg_b: 0
sg_c: 0
sg_d: 0
sg_d: 0
rbc_normal: 0
pc_normal: 0
pcc_present: 0
ba_present: 0
htn_yes: 0
dm_yes: 0
cad_yes: 0
appet_yes: 0
pe_yes: 0
ane_yes: 0

In [21]:
Future_Prediction=grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv, wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal, pcc_present, 
                                 ba_present, htn_yes, dm_yes, cad_yes, appet_yes, pe_yes, ane_yes]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]